.gitignore
[snowflake]
user = "SVC_DISTRIBUTION_DATA"
password = "<khrKV3ymWLvMg6QczKMr!!"
account = "pm58521.east-us-2.azure"
warehouse = "DISTRIBUTION_WH"
database = "DATAWAREHOUSE"
schema = "DISTRIBUTION_DATA_APPLICATION"
